<?php
$title = 'Add new product';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$product = $form->get('category_id');
$product->setAttribute('class', 'form-control');
$product->setAttribute('placeholder', 'Product category_id');

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Name');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('product', ['action' => 'add']));
$form->prepare();

/* com select
echo $this->form()->openTag($form);
echo $this->formCollection($form->get('product'));
echo $this->form()->closeTag();
*/
echo $this->form()->openTag($form);
?>
<?php  ?>
<div class="form-group">
    <?= $this->formLabel($product) ?>
    <?= $this->formElement($product) ?>
    <?= $this->formElementErrors()->render($product, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();

